//------------------------------------------------------------------------------
// registration.cpp - Autogenerated from script Entities and Components${license_text}
//------------------------------------------------------------------------------

#include "gaen/engine/Registry.h"

namespace gaen
{

${extern_cpp}

extern void register_all_entities_and_components(Registry & registry)
{
    ${calls_cpp}
}

} // namespace gaen
